name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Restore node_modules
        uses: actions/cache@v2
        id: restore-node-modules
        env:
          cache-name: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Restore NPM cache
        uses: actions/cache@v2
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        env:
          cache-name: yarn-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        run: npm run test:coverage
